all:	test-sorted-ll set-on-sorted-ll-iterative-solns set-on-sorted-ll-recursive-solns 

test-sorted-ll: test-sorted-ll.c sorted-ll.c sorted-ll.h
	gcc -o test-sorted-ll test-sorted-ll.c sorted-ll.c -I.

set-on-sorted-ll-iterative-solns: set-on-sorted-ll-iterative-solns.c sorted-ll.c sorted-ll.h
	gcc -o set-on-sorted-ll-iterative-solns set-on-sorted-ll-iterative-solns.c sorted-ll.c -I.

set-on-sorted-ll-recursive-solns: set-on-sorted-ll-recursive-solns.c sorted-ll.c sorted-ll.h
	gcc -o set-on-sorted-ll-recursive-solns set-on-sorted-ll-recursive-solns.c sorted-ll.c -I.
